name: EAS Build Android

on:
  # Permite ejecutar manualmente desde GitHub
  workflow_dispatch:
  # Se ejecuta cuando haces push a main
  push:
    branches: [main]

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Create EAS build
        run: eas build --platform android --non-interactive --clear-cache

      - name: Get build URL
        run: |
          echo "Build completed! Check your EAS dashboard for download link:"
          echo "https://expo.dev/accounts/mariaciffu/projects/itatakiManager"
